import type { SpriteRuntimeManifest } from "./types";

export const LOBSTER_ASSET_BASE_PATH = "/assets/lobster";

export const lobsterRuntimeManifest = {
  animations: {
    idle: {
      frame_paths: [
        "idle/frames/idle_01.png",
        "idle/frames/idle_02.png",
        "idle/frames/idle_03.png",
        "idle/frames/idle_04.png",
        "idle/frames/idle_05.png",
        "idle/frames/idle_04.png",
        "idle/frames/idle_03.png",
        "idle/frames/idle_02.png",
      ],
      frame_duration_ms: 125,
      loop: true,
      hold_last_frame_ms: 0,
    },
    locomotion: {
      frame_paths: [
        "locomotion/frames/locomotion_01.png",
        "locomotion/frames/locomotion_01.png",
        "locomotion/frames/locomotion_02.png",
        "locomotion/frames/locomotion_03.png",
        "locomotion/frames/locomotion_04.png",
        "locomotion/frames/locomotion_04.png",
        "locomotion/frames/locomotion_05.png",
        "locomotion/frames/locomotion_06.png",
      ],
      frame_duration_ms: 100,
      loop: true,
      hold_last_frame_ms: 0,
    },
    busy: {
      frame_paths: [
        "busy/frames/busy_01.png",
        "busy/frames/busy_02.png",
        "busy/frames/busy_03.png",
        "busy/frames/busy_04.png",
        "busy/frames/busy_05.png",
        "busy/frames/busy_06.png",
        "busy/frames/busy_05.png",
        "busy/frames/busy_04.png",
        "busy/frames/busy_03.png",
        "busy/frames/busy_02.png",
      ],
      frame_duration_ms: 100,
      loop: true,
      hold_last_frame_ms: 0,
    },
    reading: {
      frame_paths: [
        "reading/frames/reading_01.png",
        "reading/frames/reading_02.png",
        "reading/frames/reading_03.png",
        "reading/frames/reading_04.png",
        "reading/frames/reading_05.png",
        "reading/frames/reading_06.png",
        "reading/frames/reading_05.png",
        "reading/frames/reading_04.png",
        "reading/frames/reading_03.png",
        "reading/frames/reading_02.png",
      ],
      frame_duration_ms: 120,
      loop: true,
      hold_last_frame_ms: 0,
    },
    success: {
      frame_paths: [
        "success/frames/success_01.png",
        "success/frames/success_02.png",
        "success/frames/success_03.png",
        "success/frames/success_03.png",
        "success/frames/success_04.png",
        "success/frames/success_05.png",
        "success/frames/success_06.png",
        "success/frames/success_06.png",
      ],
      frame_duration_ms: 140,
      loop: false,
      hold_last_frame_ms: 450,
    },
    error: {
      frame_paths: [
        "error/frames/error_01.png",
        "error/frames/error_02.png",
        "error/frames/error_03.png",
        "error/frames/error_03.png",
        "error/frames/error_04.png",
        "error/frames/error_05.png",
        "error/frames/error_06.png",
        "error/frames/error_06.png",
      ],
      frame_duration_ms: 166,
      loop: false,
      hold_last_frame_ms: 700,
    },
  },
  runtime_state_map: {
    session_state_to_animation: {
      idle: "idle",
      starting: "idle",
      running: "idle",
      pause_requested: "idle",
      paused: "idle",
      waiting_for_approval: "idle",
      takeover: "idle",
      completed: "success",
      failed: "error",
      stopped: "idle",
    },
    action_type_to_animation: {
      navigate: "busy",
      click: "busy",
      type: "busy",
      scroll: "busy",
      read: "reading",
      wait: "idle",
      complete: "success",
      error: "error",
    },
    moving_animation: "locomotion",
  },
} satisfies SpriteRuntimeManifest;
