from __future__ import annotations

from typing import Any, Protocol


class AdapterConnector(Protocol):
    adapter_id: str
    capabilities: dict[str, bool]

    async def start_task(
        self,
        task_text: str,
        demo_mode: bool = False,
        web_mode: str | None = None,
        web_bridge: str | None = None,
        auto_delegate: bool = False,
        observer_mode: bool = False,
        observed_session_id: str | None = None,
        bridge_context: dict[str, Any] | None = None,
    ) -> None: ...
    async def pause(self) -> None: ...
    async def resume(self) -> None: ...
    async def approve(self, checkpoint_id: str) -> None: ...
    async def reject(self, checkpoint_id: str) -> None: ...
    async def accept_bridge(self) -> None: ...
    async def decline_bridge(self) -> None: ...
    async def remote_mouse_move(self, x: float, y: float) -> None: ...
    async def remote_mouse_down(self, x: float, y: float, button: str = "left") -> None: ...
    async def remote_mouse_up(self, x: float, y: float, button: str = "left") -> None: ...
    async def remote_click(self, x: float, y: float, button: str = "left") -> None: ...
    async def remote_scroll(self, delta_x: float, delta_y: float) -> None: ...
    async def remote_key_down(self, key: str) -> None: ...
    async def remote_key_up(self, key: str) -> None: ...
    async def start_takeover(self) -> None: ...
    async def end_takeover(self) -> None: ...
    async def stop(self) -> None: ...
